parameters:
    pim_dashboard.widget.registry.class:        Pim\Bundle\DashboardBundle\Widget\Registry
    pim_dashboard.widget.completeness.class:    Pim\Bundle\DashboardBundle\Widget\CompletenessWidget
    pim_dashboard.widget.links.class:           Pim\Bundle\DashboardBundle\Widget\LinksWidget
    pim_dashboard.widget.last_operations.class: Pim\Bundle\DashboardBundle\Widget\LastOperationsWidget

services:
    pim_dashboard.widget.registry:
        class: '%pim_dashboard.widget.registry.class%'

    ##
    # Widgets
    ##
    pim_dashboard.widget.links:
        class: '%pim_dashboard.widget.links.class%'
        arguments:
            - '@oro_security.security_facade'
            -
                -
                    acl: pim_enrich_product_index
                    route: pim_enrich_product_index
                    label: pim_dashboard.link.label.product
                    image: widget_artikel_bearbeiten.png
                -
                    acl: pim_enrich_family_index
                    route: pim_enrich_family_index
                    click: addProd(); 
                    label: pim_dashboard.link.label.addproduct
                    image: widget_artikel_hinzufuegen.png
                -
                    acl: pim_enrich_attribute_index
                    route: pim_enrich_attribute_index
                    label: pim_dashboard.link.label.attribute
                    image: widget_produktqualitaet.png
        tags:
            - { name: pim_dashboard.widget, position: 10 }

    pim_dashboard.widget.completeness:
        class: '%pim_dashboard.widget.completeness.class%'
        arguments:
            - '@pim_catalog.repository.completeness'
            - '@pim_catalog.helper.locale'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.repository.locale'
        tags:
            - { name: pim_dashboard.widget, position: 20 }

    pim_dashboard.widget.last_operations:
        class: '%pim_dashboard.widget.last_operations.class%'
        arguments:
            - '@pim_import_export.manager.job_execution'
            - '@translator'
            - '@pim_catalog.localization.presenter.datetime'
            - '@security.token_storage'
            - '@oro_security.security_facade'
        tags:
            - { name: pim_dashboard.widget, position: 30 }
